// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from directory_tree.djinni

#include "NativeDirectoryTree.hpp"  // my header
#include "Marshal.hpp"
#include "NativeDirectory.hpp"

namespace djinni_generated {

NativeDirectoryTree::NativeDirectoryTree() : ::djinni::JniInterface<::synclib::DirectoryTree, NativeDirectoryTree>("de/jb/synclib/DirectoryTree$CppProxy") {}

NativeDirectoryTree::~NativeDirectoryTree() = default;


CJNIEXPORT void JNICALL Java_de_jb_synclib_DirectoryTree_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::synclib::DirectoryTree>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_de_jb_synclib_DirectoryTree_buildFromJson(JNIEnv* jniEnv, jobject /*this*/, jstring j_json)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::synclib::DirectoryTree::buildFromJson(::djinni::String::toCpp(jniEnv, j_json));
        return ::djinni::release(::djinni_generated::NativeDirectory::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
