// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stream.djinni

#include "NativeInputStream.hpp"  // my header

namespace djinni_generated {

NativeInputStream::NativeInputStream() : ::djinni::JniInterface<::synclib::InputStream, NativeInputStream>("de/jb/synclib/InputStream$CppProxy") {}

NativeInputStream::~NativeInputStream() = default;


CJNIEXPORT void JNICALL Java_de_jb_synclib_InputStream_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::synclib::InputStream>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
