// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from repository.djinni

#pragma once

#include "Repository.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeRepository final : ::djinni::JniInterface<::synclib::Repository, NativeRepository> {
public:
    using CppType = std::shared_ptr<::synclib::Repository>;
    using CppOptType = std::shared_ptr<::synclib::Repository>;
    using JniType = jobject;

    using Boxed = NativeRepository;

    ~NativeRepository();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeRepository>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeRepository>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeRepository();
    friend ::djinni::JniClass<NativeRepository>;
    friend ::djinni::JniInterface<::synclib::Repository, NativeRepository>;

};

}  // namespace djinni_generated
