// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from directory_tree.djinni

#pragma once

#include "FileCompareResult.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeFileCompareResult final : ::djinni::JniEnum {
public:
    using CppType = ::synclib::FileCompareResult;
    using JniType = jobject;

    using Boxed = NativeFileCompareResult;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeFileCompareResult>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeFileCompareResult>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeFileCompareResult() : JniEnum("de/jb/synclib/FileCompareResult") {}
    friend ::djinni::JniClass<NativeFileCompareResult>;
};

}  // namespace djinni_generated
