// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from directory_tree.djinni

#pragma once

#include "DirectoryTree.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeDirectoryTree final : ::djinni::JniInterface<::synclib::DirectoryTree, NativeDirectoryTree> {
public:
    using CppType = std::shared_ptr<::synclib::DirectoryTree>;
    using CppOptType = std::shared_ptr<::synclib::DirectoryTree>;
    using JniType = jobject;

    using Boxed = NativeDirectoryTree;

    ~NativeDirectoryTree();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeDirectoryTree>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeDirectoryTree>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeDirectoryTree();
    friend ::djinni::JniClass<NativeDirectoryTree>;
    friend ::djinni::JniInterface<::synclib::DirectoryTree, NativeDirectoryTree>;

};

}  // namespace djinni_generated
