// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from directory_tree.djinni

#pragma once

#include "File.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeFile final {
public:
    using CppType = ::synclib::File;
    using JniType = jobject;

    using Boxed = NativeFile;

    ~NativeFile();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeFile();
    friend ::djinni::JniClass<NativeFile>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("de/jb/synclib/File") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V") };
    const jfieldID field_mName { ::djinni::jniGetFieldID(clazz.get(), "mName", "Ljava/lang/String;") };
    const jfieldID field_mPath { ::djinni::jniGetFieldID(clazz.get(), "mPath", "Ljava/lang/String;") };
    const jfieldID field_mHash { ::djinni::jniGetFieldID(clazz.get(), "mHash", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
