// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from directory_tree.djinni

#pragma once

#include "Directory.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeDirectory final : ::djinni::JniInterface<::synclib::Directory, NativeDirectory> {
public:
    using CppType = std::shared_ptr<::synclib::Directory>;
    using CppOptType = std::shared_ptr<::synclib::Directory>;
    using JniType = jobject;

    using Boxed = NativeDirectory;

    ~NativeDirectory();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeDirectory>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeDirectory>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeDirectory();
    friend ::djinni::JniClass<NativeDirectory>;
    friend ::djinni::JniInterface<::synclib::Directory, NativeDirectory>;

};

}  // namespace djinni_generated
