// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stream.djinni

#include "NativeOutputStream.hpp"  // my header
#include "NativeInputStream.hpp"

namespace djinni_generated {

NativeOutputStream::NativeOutputStream() : ::djinni::JniInterface<::synclib::OutputStream, NativeOutputStream>("de/jb/synclib/OutputStream$CppProxy") {}

NativeOutputStream::~NativeOutputStream() = default;


CJNIEXPORT void JNICALL Java_de_jb_synclib_OutputStream_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::synclib::OutputStream>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_de_jb_synclib_OutputStream_00024CppProxy_native_1copy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_from)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::synclib::OutputStream>(nativeRef);
        ref->copy(::djinni_generated::NativeInputStream::toCpp(jniEnv, j_from));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
