// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from directory_tree.djinni

package de.jb.synclib;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import java.util.ArrayList;

/**
 * Represents the differences between two directories
 * This struct is obtained using the static directory::compare_files(a, b) method
 */
public final class CompareResult {


    /*package*/ final ArrayList<File> mOnlyInA;

    /*package*/ final ArrayList<File> mOnlyInB;

    /*package*/ final ArrayList<File> mConflicting;

    public CompareResult(
            @NonNull ArrayList<File> onlyInA,
            @NonNull ArrayList<File> onlyInB,
            @NonNull ArrayList<File> conflicting) {
        this.mOnlyInA = onlyInA;
        this.mOnlyInB = onlyInB;
        this.mConflicting = conflicting;
    }

    /** Files that exist in directory a but not in b */
    @NonNull
    public ArrayList<File> getOnlyInA() {
        return mOnlyInA;
    }

    /** Files that exist in directory b but not in a */
    @NonNull
    public ArrayList<File> getOnlyInB() {
        return mOnlyInB;
    }

    /** Files that exist in both directories with different hash values */
    @NonNull
    public ArrayList<File> getConflicting() {
        return mConflicting;
    }

    @Override
    public String toString() {
        return "CompareResult{" +
                "mOnlyInA=" + mOnlyInA +
                "," + "mOnlyInB=" + mOnlyInB +
                "," + "mConflicting=" + mConflicting +
        "}";
    }

}
