// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from directory_tree.djinni

package de.jb.synclib;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

public final class File {


    /*package*/ final String mName;

    /*package*/ final String mHash;

    public File(
            @NonNull String name,
            @NonNull String hash) {
        this.mName = name;
        this.mHash = hash;
    }

    @NonNull
    public String getName() {
        return mName;
    }

    @NonNull
    public String getHash() {
        return mHash;
    }

    @Override
    public String toString() {
        return "File{" +
                "mName=" + mName +
                "," + "mHash=" + mHash +
        "}";
    }

}
