// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from directory_tree.djinni

package de.jb.synclib;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

public enum FileCompareResult {
    /** The compared files are unrelated */
    UNRELATED,
    /** The compared files have the same path and content */
    EQUAL,
    /** The compared files have the same path but different contents */
    CONFLICTING,
    ;
}
