// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from directory_tree.djinni

#pragma once

#include "File.hpp"
#include <utility>
#include <vector>

namespace synclib {

/**
 * Represents the differences between two directories
 * This struct is obtained using the static directory::compare_files(a, b) method
 */
struct CompareResult final {
    /** Files that exist in directory a but not in b */
    std::vector<File> onlyInA;
    /** Files that exist in directory b but not in a */
    std::vector<File> onlyInB;
    /** Files that exist in both directories with different hash values */
    std::vector<File> conflicting;

    CompareResult(std::vector<File> onlyInA_,
                  std::vector<File> onlyInB_,
                  std::vector<File> conflicting_)
    : onlyInA(std::move(onlyInA_))
    , onlyInB(std::move(onlyInB_))
    , conflicting(std::move(conflicting_))
    {}
};

}  // namespace synclib
