// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from directory_tree.djinni

#pragma once

#include <memory>
#include <string>
#include <vector>

namespace synclib {

struct File;

class Directory {
public:
    virtual ~Directory() {}

    virtual std::string getName() const = 0;

    virtual bool isRoot() const = 0;

    virtual std::vector<std::shared_ptr<Directory>> getSubdirectories() const = 0;

    virtual std::vector<File> getFiles(bool recursive) const = 0;
};

}  // namespace synclib
