// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from directory_tree.djinni

#pragma once

#include <string>
#include <utility>

namespace synclib {

struct File final {
    /** the file name including the extension if there is one */
    std::string name;
    /** the path relative to the root directory of the repository */
    std::string path;
    /** a hash of the file contents */
    std::string hash;

    File(std::string name_,
         std::string path_,
         std::string hash_)
    : name(std::move(name_))
    , path(std::move(path_))
    , hash(std::move(hash_))
    {}
};

}  // namespace synclib
