// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from directory_tree.djinni

#pragma once

#include <string>
#include <utility>

namespace synclib {

struct File final {
    std::string name;
    std::string hash;

    File(std::string name_,
         std::string hash_)
    : name(std::move(name_))
    , hash(std::move(hash_))
    {}
};

}  // namespace synclib
