// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stream.djinni

#pragma once

namespace synclib {

class InputStream {
public:
    virtual ~InputStream() {}
};

}  // namespace synclib
