// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stream.djinni

#pragma once

#include <memory>

namespace synclib {

class InputStream;

class OutputStream {
public:
    virtual ~OutputStream() {}

    virtual void copy(const std::shared_ptr<InputStream> & from) = 0;
};

}  // namespace synclib
