// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from repository.djinni

#pragma once

#include <memory>
#include <string>

namespace synclib {

class Directory;
class InputStream;
class OutputStream;
struct File;

class Repository {
public:
    virtual ~Repository() {}

    virtual std::shared_ptr<Directory> getDirectoryTree() = 0;

    virtual std::shared_ptr<InputStream> read(const File & from) const = 0;

    virtual std::shared_ptr<OutputStream> write(const File & to) = 0;

    virtual void remove(const File & file) = 0;

    static std::shared_ptr<Repository> createFromFileSystem(const std::string & directoryPath);
};

}  // namespace synclib
